### ISSUE TITLE
Code doesn't compile on Linux

### ISSUE THREAD

**Issue by sheharyarn** [eyewriter/eyewriter#16]
I've been trying to run [EyeWriter 2.1](https://github.com/jasonwebb/eyewriter) by  @jasonwebb on Ubuntu 13.10 using `OpenFrameworks 0.7.4` and `CodeBlocks 12.11`.

At first there was the initial dependency issue which was simply fixed by replacing all instances of `/win_cb/` with `/linux/` in the project files. But now, it doesn't detect Header Files which I can see are present. Files like `tesseler.h` and `ofMesh.h` are still unresolved.

Has anyone been able to run the code on Linux? Or at least know how can these issues be fixed? @jasonwebb, @ofZach, @openframeworks - What do you guys think?

I'm quite new to OF and CodeBlocks and would appreciate any help I could get. Thanks!

**Comment by ofZach** [comment]
I don't think you can just convert the windows codeblocks file to linux this way.  

I'd start by making a linux project that has the necessary addons (see readme file for the list) and then add in the source code manually
