### ISSUE TITLE
Inaccuracies

### ISSUE THREAD

**Issue by TahirHussain** [eyewriter/eyewriter#19]
Sir, we completed the development of software and completed the hardware design.But there are some inaccuracies in it. Please check them and please provide help in clearing the issue.
![eye](https://cloud.githubusercontent.com/assets/6647144/3604863/ec8deb3c-0d24-11e4-99d3-78da6230241f.JPG)
![capturem](https://cloud.githubusercontent.com/assets/6647144/3604879/04a92ede-0d25-11e4-8283-f401dc68fab2.JPG)
![img_20140603_190724](https://cloud.githubusercontent.com/assets/6647144/3604913/74af8264-0d25-11e4-8426-ead2dbf71fc1.jpg)

**Comment by ofZach** [comment]
it looks like your bright eye is not bright enough / giving proper bright eye effect -- can you please mount the LEDS as close as possible to the camera lens and see if that helps?

**Comment by TahirHussain** [comment]
Ok sir.. I will check that.. and thanks

**Comment by Shyckh** [comment]
is your hardware working fine ?

**Comment by Mrpedi** [comment]
i have also inaccuracy problems like @TahirHussain .  can anyone help?
![screenshot 2014-08-16 19 08 44](https://cloud.githubusercontent.com/assets/8499869/3977487/ccf8ceba-2839-11e4-8260-937aec86e329.png)

**Comment by ofZach** [comment]
this looks like you are not getting strobing working (I see on both frames, all three lights on).  you need to have the center light happen alternatively to the outer lights.

**Comment by ofZach** [comment]
here, (from the top picture) you can see the alternation.  the problem with this one is that the center LEDs need to be more on axis / co-incident with the lense to get the bright eye effect : 

![screen shot 2014-08-20 at 6 36 02 am](https://cloud.githubusercontent.com/assets/142897/3979539/e4853eee-2855-11e4-93fb-73bf70269729.png)

in your image, @Mrpedi there doesn't seem to be alternation...  (also, you will need to work on your bright eye image once the alternation is happening).

**Comment by Mrpedi** [comment]
Thank you sir. Is it vsync issue(from camera) or circuitry? Thanks in advance

**Comment by ofZach** [comment]
it's hard to see where the error is, can you check that you did this page right?

http://www.instructables.com/id/The-EyeWriter-20/step9/Hacking-the-PS-Eye-camera-VSync/

in particular, pay attention to: 

Locate the Ground joint on your PS Eye board. Some PS Eye models have 5 joints near the lens mount (left image below), while some have 4 joints (right image below). If your model has 5 joints, the Ground joint is at the end closest to the lens mount. If your model has 4 joints, the Ground joint is also at the end closest to the lens mount, and twice as wide as the other joints. see image here

**Comment by Shyckh** [comment]
I am having the same issue vsync signal works fine but alteration is not being seen on bright and dark image accurately. Leds wouldnot turn off properly. Do i have to use pull down resistance on fet or i have to use veriable resistor of greater value rather than of 25 ohms.

**Comment by ofZach** [comment]
pinging @itotaka for electrical / led questions...

**Comment by Shyckh** [comment]
@ofZach the central led is flikering turning on and off rapidly. but other leds are not fully turning off.do these leds have to be fully turn on and off also in order get accuracy? i don't think so @itotaka  is alive on this forum.
@TahirHussain  can you please upload the picture of your circuit also?

**Comment by ofZach** [comment]
@Shyckh sorry, I don't know much about the electronics, pinging @itotaka @jmsaavedra who know a bit more about the electrical side of things.

**Comment by Shyckh** [comment]
@ofZach  there are two codes one is strobeeye.pde and other is greystrobeeye.pde. I uploaded strobe eye.pde to arduino. is itcorrect code to uplaod on arduino? And also grey strobe eye.pde is used for what purpose. Thanks Sir for replying

**Comment by ofZach** [comment]
I think grey strobe is specifically for point grey cameras, and strobeeye is for eye sight cameras, which you are using so it should be strobeeye.pde that you use.

**Comment by itotaka** [comment]
Sorry for delay!

@Shyckh I don't think you need to add something to the circuit.

> the central led is flikering turning on and off rapidly. but other leds are not fully turning off

mmm, strange. You should check your circuit or bread board/PSEYE/parts again. Especially VSYNC part of PSEYE is very fragile. You are using exactly the same electrical parts as we used, right?
Parts list: http://eyewriter.org/docs/PartsList_EyeWriter2.pdf

**Comment by Shyckh** [comment]
@itotaka you are right circuit is simple and it should work. i am using irl530 fets. first i have tried the circuit with 2n2222 transistor but it dose not work. i have checked the transistor its is working good. then i recheck the vsync signal as in eyewriter 2 pdf. its also working. i remove transistor and used a 555 timer with output pulse set to 16.6 ms as in PAL and NTAC stadard says. i also tried using c1383 transistor. i also changed the pins of arduino but can't get strobing working. now i am planing to change arduino board... but on this board other program is working fine. also i have tried using vsync signal directly to arduino but no succecss at all.

**Comment by Shyckh** [comment]
@itotaka  also correct me if i am wrong. From the full circuit it is apparent that when we turn on the Supply all leds will turn on untill they have been gated i.e gate pulse will be applied on them so that leds start flicker. but don't you think that there should be some capacitance developed in fet which alter them to some unknown voltage.

**Comment by TahirHussain** [comment]
After so many years, I came back to respond to this issue.
Actually, at that time, we didn't remove the filter from the camera, which was causing this issue.
