### ISSUE TITLE
library issues

### ISSUE THREAD

**Issue by samaarifsam** [eyewriter/eyewriter#20]
i am facing some problems while building the code. can u plz help.
i'm attaching the snap of problem.
![zac](https://cloud.githubusercontent.com/assets/8209561/3635177/81cb8d7e-0f61-11e4-8a86-edc29b1b0f0f.JPG)

**Comment by ofZach** [comment]
what version of OF / windows / CB ?

maybe this forum post is helpful?
http://forum.openframeworks.cc/t/new-code-blocks-10-05-quot-exit-is-not-a-member-quot-fix/4048

**Comment by samaarifsam** [comment]
of_preRelease_v0061_win_cb

**Comment by samaarifsam** [comment]
i corrected these errors, bt nw um caught uop in these:

![errr](https://cloud.githubusercontent.com/assets/8209561/3637118/30896d8e-0ff5-11e4-9251-a9ebe9dcd17f.JPG)

**Comment by TahirHussain** [comment]
![rtty](https://cloud.githubusercontent.com/assets/6647144/3711564/5d64be26-14dc-11e4-9702-580efcebd75b.JPG)
Thanks.. it worked now...

**Comment by hdba** [comment]
@TahirHussain Can you use (compile-run) the eyewriter program correctly in windows??

**Comment by TahirHussain** [comment]
@hdba yes ..

**Comment by hdba** [comment]
i have some problems using (eyewriter 2.0) them correctly in Visual studio and/or CodeBlocks; can you help me to find were are my mistakes? what files you use to run the project?

**Comment by TahirHussain** [comment]
Can you tell me in detail how you compiled it. I mean what OS , which openframeworks version , you have used?

**Comment by hdba** [comment]
I have windows 7 ultimate,  visual studio 2012 and code blocks 10.05, i download the openfreamworks in the oficial page and it is 0.8.3 i think

**Comment by hdba** [comment]
And i use the files of the page instructables of eyewriter 2.0 but i think that most or all of those file are for osx

**Comment by hdba** [comment]
@TahirHussain what program you use and what files?

**Comment by samaarifsam** [comment]
use 0.6 version of oF.

**Comment by hdba** [comment]
In visual or codeblocks what is better?

**Comment by ofZach** [comment]
there are not visual studio project files for this project -- use codeblocks.

**Comment by hdba** [comment]
ok @ofZach , i download two folders where in each folder has a "file.exe" and one of them show me the screen of @TahirHussain but in the moment to calibrate the green cirlce doesn't appear and have the options of calibrate, catch me, writing and drawing and the other one show me a similiar screen but only a scren with 4 views of the camera, calibrate and catch me but the green circle apper and i can use the catch me very well, in these two folders i did NOT use code blocks, i am in the way?? what is the problem of the file that has the severals screens??

**Comment by ofZach** [comment]
sorry, I don't understand the question

**Comment by hdba** [comment]
![program1](https://cloud.githubusercontent.com/assets/8610139/4143917/5b1d08be-33d4-11e4-988c-6a084595b5e2.jpg)
![program2](https://cloud.githubusercontent.com/assets/8610139/4143921/64e76e0c-33d4-11e4-9679-49ead917bb67.jpg)

**Comment by hdba** [comment]
i have this programs but i not use codeblocks to opened, are apps in the format (.EXE) on the second screen the green circle to move into the program does not appear, why??

**Comment by ofZach** [comment]
I believe the green dot appears after you calibrate.  It doesn't look like you have a good physical setup yet for the 2.0 eyewriter  (there's not bright eye effect or strobing / alternating) -- can you show us your setup?

**Comment by hdba** [comment]
no no appear when i end the calibration,  yes i do not have all of the physical setup but i have all the stuff, but first i want to be sure that i have the correct software

**Comment by hdba** [comment]
the sketch of the arduino have something that affect in the software??

**Comment by ofZach** [comment]
the software is fine - arduino code sketch alters the arduino to respond to the vsync from the camera and blink the leds.

**Comment by hdba** [comment]
ok, let me check with all the stuff; thanks i really appreciate your time i hope so to finally work, i know that we are very close

**Comment by hdba** [comment]
i have all the stuff but it still not working, first i change a few things because i do not found it, i have the power supply of 5v/600mA, the mosfet N is 50v/53A, pot of 50k, and the transistor is 2n2222a, the led blink with the arduino but with the IR leds doesnt, i have the ps3 eye camera with the vsync hack; the software still not working, the same problem the green dot not appear in the moment of the calibration, the change of the components affect to the circuit?? i do not have the software correctly??

**Comment by ofZach** [comment]
are the IR LEDs blinking?  I think you will need that and if not, please check the circuit again.   Video or pictures help here for us to help you.

**Comment by hdba** [comment]
i change all the stuff to the eyewriter 1.0 project and its the same problem in the software, the green dot doesnt appear, i have some files but only two of them open but only one of them works (and no work at all only have the option of "catch me" ) i attach the images:
this are the files that i have:
![image](https://cloud.githubusercontent.com/assets/8610139/4228426/586f6c2e-395b-11e4-8dc5-3b5e0065343b.jpg)

in this program only contain: the adjustments, calibration and the catch me option
![image1](https://cloud.githubusercontent.com/assets/8610139/4228432/7da2c644-395b-11e4-85e1-9883d599409c.jpg)

in this program contain: the adjustments, calibration, catch me, drawing, writing and the speed of a dot (the only thing that works is the adjustments, the green dot doesnt appear after the calibration )
![image2](https://cloud.githubusercontent.com/assets/8610139/4228466/251be856-395c-11e4-8c1a-057a6887da7b.jpg)

**Comment by ofZach** [comment]
you do not seem to have strobing working, you'd see two different images for input bright and input dark, which finds the eye, as per: 

https://cloud.githubusercontent.com/assets/6647144/3711564/5d64be26-14dc-11e4-9702-580efcebd75b.JPG

can you please document your physical construction?

**Comment by hdba** [comment]
when i can see the same on my screen will work i got it, doesn't matter that i do the eyewriter glasses or the eyewriter 2.0 the screen of the inputs will be the same ?

**Comment by ofZach** [comment]
I don't understand the question.  You are building the eyewriter 2 system, I'm trying to help you get it to work and telling you that something looks wrong with your hardware here.

**Comment by hdba** [comment]
Mmm more easier, what system is more simple or easier to do?: the objective to see is as the picture you show me?

**Comment by ofZach** [comment]
the eyewriter 1.0 system is simpler, but it doesn't handle head rotation or translation well.

**Comment by hdba** [comment]
Oks, but the software or the app to use is the same for the project 1 and project 2?

**Comment by Anpey9** [comment]
@ofZach i need help plz with the project can i have your email
My email is kokoelromany12@gmail.com

**Comment by Anpey9** [comment]
@TahirHussain Can i communicate with you plz I need help with the project
My email is kokoelromany12@gmail.com 
Plz contact me
