### ISSUE TITLE
Problems compiling with C::B and OF 

### ISSUE THREAD

**Issue by Becky2093** [eyewriter/eyewriter#23]
Hello,

I am quite fond of the idea that this software proposes, however the implementation of this software has been anything but easy.  

The current issue I am facing is error: "ofxHelperFile.h"  no such file or directory

I'm using C::B 10.05 and OF FAT Pre-Release v.0062.  

I have openframeworks installed in the path c:\openframeworks
I then have the eyewriter-master files installed in c:\openframeworks\apps

The ofxFileHelper folder is located under C:\openframeworks\apps\eyewriter-master\eyeWriterTracker\src\addons\ofxFileHelper

Is this located in the wrong place? Is there something I'm missing? I've resorted to the older versions of C::B and OF because of issues I was facing with the newer versions.  

Thank you,
Becky

P.S. A how to install the eyewriter software for dummies step-by-step manual would be very helpful to me and the ALS patients to whom I plan to refer this if I can get it working.

**Comment by ofZach** [comment]
are you compiling the eyewriter 1.0 code (glasses) or 2.0 (http://www.instructables.com/id/The-EyeWriter-20/) ?   Are you using code from this git repo?   I will take a look at windows but I'm pretty sure the both code bases are more modern then that so the version of OF should be newer.    I'm sorry about the problems and happy to help

**Comment by Becky2093** [comment]
Thanks for getting back so quickly!

I'm compiling eyewriter 2.0, using the code from this git repo.  
.  
Do you have a tried and true version of OF and C::B that you recommend to work with this software?  

Thank you for your help!!

**Comment by Becky2093** [comment]
UPDATE: I tried updating C::B & OF to their newest versions (13.12 and 0.8.4).  When EyeWriter unsuccessfully compiled, I discovered through online forums that OF isn't completely up to the speed of C::B. I regressed to C::B 12.11 and v.0.8.0 again without success and continued downgrading to v.0.7.4 with C::B (as openFrameworks suggested this as being the most compatible).  Each time I received the errors "fatal error: gl\glew.h: no such file or directory" for the line #include "GL\glew.h" in the ofConstants.h

I'm able to eliminate this error by finding the file manually and inserting the path (i.e. C:/.../.../.../glew.h). However, there are many many more errors similar to this which causes the manual correction to be very tedious.

I'm suspecting that the problem is due to my newb ignorance of the proper file structure. I haven't changed the structure from the zipped file.

Location of Workspace:  C:\openframeworks\apps\eyewriter-master\eyeWriterTracker\RemoteEyeTracker.workspace
Location of glew.h:    C:\openframeworks\libs\openFrameworks\gl\glew.h

Any suggestions of how to restructure this? Thank you.

**Comment by igormp** [comment]
I'm having this same problem, probably because I'm also doing something wrong according to the file structure, any light on how to solve it for a newbie?

**Comment by Becky2093** [comment]
I found a workaround.  Hope this helps. 

Download Code::Blocks 12.11 with mingw http://www.codeblocks.org/downloads/5
    Unzip and install to a location on your computer
    We saved to C:\Program Files\ and created the CodeBlocks folder here

Download Code::Blocks Additions  by navigating to this link http://danielmclaren.com/2009/09/12/setting-up-openframeworks-with-codeblocks
And selecting the OpenFrameworks Additions for Code::Blocks
    Unzip the file
        The location does not matter as all files will be moved regardless

Add the contents of the folder "add_to_codeblocks_mingw_include" into "C:\Program Files\CodeBlocks\MinGW\include" (or wherever your app\mingw\include is)

Add the contents of the folder "add_to_codeblocks_mingw_lib" into "C:\Program Files\CodeBlocks\MinGW\lib" (or wherever your app\mingw\lib is)

Download Openframeworks v.0.7.4   http://openframeworks.cc/download/older.html
    Save to your local drive (C:) 

WINDOWS users navigate to https://onedrive.live.com/?cid=f966c677a7c86219&sc=documents&id=F966C677A7C86219!103
And download RemoteEyeTrackerWindows zip file. Save to C:\openframeworks\apps
Finally, purchase and download the driver for the PS3 Eye from https://codelaboratories.com/downloads

If, when you open the C:\openframeworks\app\RemoteEyeTracker.exe the camera is default to your computer’s webcam you will have to disable this. UNPLUG YOUR PS3 EYE before proceeding. Open the control panel and selecting hardware/devices and opening the device manager.  In the device manager, your webcam should be found under imaging devices. Right click on the name of the webcam and select “disable.” Now you may reattach your PS3 Eye 

You might have to update your inputsettings to set the device id for the camera.  Do so by navigating to C:\openframeworks\apps\data\Settings and opening inputSettings.xml with a text editor such as wordpad.  Change the device id to 2. Save and close this file.  

When you execute the RemoteEyeTracker.exe file, you should now be seeing the input from your PS3 Eye.

**Comment by theEvilbyteS** [comment]
Hi, can you re-upload RemoteEyeTrackerWindows.zip pls, im going crazy with the tries of source compilation...
